# Generated by Django 3.0.6 on 2020-05-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField(verbose_name='created')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('contact', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=40)),
            ],
        ),
    ]
