# Generated by Django 3.0.6 on 2020-05-18 13:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 13, 39, 58, 341775, tzinfo=utc), verbose_name='created'),
            preserve_default=False,
        ),
    ]
