# Generated by Django 3.0.6 on 2020-05-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contact',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=' ', max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
